### ISSUE TITLE
비디오 미선택상태에서 Play 누르면 크래시

### ISSUE THREAD

**Issue by byeongkeunahn** [YonghoAhn/WPFWallpaper#3]
비디오가 선택 안 돼 있으면 WebBrowser1.Navigate의 Url이 null로 전달돼서 ArgumentNullException으로 죽음
--> 안내창 띄우든지 Play 버튼을 숨김/비활성화하든지 해야됨

그리고 비디오 선택이 클릭으로 안돼고 꼭 더블클릭으로 해야만 되는 거 처음보면 모름
클릭으로도 되도록

**Comment by YonghoAhn** [comment]
fixed
